development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://localhost:9292/faye" # https://priv-pub.herokuapp.com/faye
  secret_token: "secret"
  signature_expiration: 3600 # one hour
